import { NextRequest, NextResponse } from "next/server";
import { RailRadarError, searchStations, type Station } from "@/lib/railradar";
import { firstIssueMessage, stationSearchQuerySchema } from "@/lib/schemas";
import { clientKey, stationSearchLimiter } from "@/lib/rateLimit";

/**
 * Station search — **fallback only. Every miss here costs a RailRadar request.**
 *
 * The autocomplete no longer calls this while you type. It searches
 * `lib/data/mumbai-stations.json`, generated by `scripts/build-stations.mts` and
 * committed to the repo, entirely in the browser. This route survives for the
 * one case the bundle can't answer: a station added to the network since the
 * bundle was generated, reached by an explicit "search all stations" tap.
 *
 * If this route's traffic ever climbs, that is a bug or an out-of-date bundle,
 * not growth. Regenerate the bundle (`npm run stations:refresh`) rather than
 * raising the limits below.
 */

const MAX_RESULTS = 8;
const MIN_QUERY_LENGTH = 2;

/**
 * Answered locally, so a short or empty query never reaches RailRadar. Cheap
 * to serve and it keeps a stray client loop from costing anything.
 */
const EMPTY_RESULT_CACHE_CONTROL = "public, s-maxage=86400";

/** A real lookup is worth caching hard: station names do not move. */
const RESULT_CACHE_CONTROL = "public, s-maxage=86400, stale-while-revalidate=604800";

export async function GET(request: NextRequest) {
  const limit = stationSearchLimiter.check(clientKey(request.headers));
  if (!limit.ok) {
    return NextResponse.json(
      {
        error: "Please wait a minute and try again.",
        kind: "RATE_LIMIT",
      },
      {
        status: 429,
        headers: { "Retry-After": String(limit.retryAfterSeconds) },
      }
    );
  }

  const parsed = stationSearchQuerySchema.safeParse({
    q: request.nextUrl.searchParams.get("q") ?? "",
  });

  if (!parsed.success) {
    return NextResponse.json(
      { error: firstIssueMessage(parsed.error), kind: "VALIDATION" },
      { status: 400 }
    );
  }

  const { q } = parsed.data;

  // Not an error: the user is still typing. Answering locally also keeps a
  // one-letter keystroke from spending an upstream request.
  if (q.length < MIN_QUERY_LENGTH) {
    return NextResponse.json(
      { stations: [] satisfies Station[] },
      { headers: { "Cache-Control": EMPTY_RESULT_CACHE_CONTROL } }
    );
  }

  try {
    const stations = await searchStations(q);

    // This app only serves the Mumbai suburban network, and RailRadar's
    // fuzzy match otherwise surfaces a lot of unrelated stations for short queries.
    const filtered = stations
      .filter((s) => s.isActive && s.city?.toLowerCase() === "mumbai")
      .sort((a, b) => b.popularity - a.popularity)
      .slice(0, MAX_RESULTS);

    return NextResponse.json(
      { stations: filtered },
      { headers: { "Cache-Control": RESULT_CACHE_CONTROL } }
    );
  } catch (err) {
    if (err instanceof RailRadarError) {
      const status = err.kind === "RATE_LIMIT" ? 429 : 502;
      return NextResponse.json({ error: err.message, kind: err.kind }, { status });
    }
    return NextResponse.json(
      { error: "Something went wrong while searching for stations.", kind: "UNKNOWN" },
      { status: 500 }
    );
  }
}
